services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=auctionsDB

  auction-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auction-app
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB=auctionsDB
    env_file:
      - ./cmd/auction/.env
    restart: unless-stopped

volumes:
  mongo_data: